let moveMotorZIP = Kitronik_Move_Motor.createMoveMotorZIPLED(4)
moveMotorZIP.setZipLedColor(0, Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Blue))
moveMotorZIP.setZipLedColor(1, Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Green))
moveMotorZIP.setZipLedColor(2, Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Orange))
moveMotorZIP.setZipLedColor(3, Kitronik_Move_Motor.colors(Kitronik_Move_Motor.ZipLedColors.Indigo))
Kitronik_Move_Motor.beepHorn()
moveMotorZIP.show()
Kitronik_Move_Motor.brakeLightsOff()
basic.forever(function () {
    Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Forward, 10)
    Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Reverse, 5)
    moveMotorZIP.show()
    moveMotorZIP.rotate(1)
    basic.pause(100)
})
